FROM node:14.17.1
WORKDIR /app

COPY ./package*.json ./
RUN npm ci

COPY src ./src
CMD [ "npm", "run", "crons-tx-users" ]

# docker build -f Dockerfile_Cron_Users . -t xoycoin/xoycoin-exchange-cron-users
# docker run --name xoycoin-exchange-cron-users --env-file ./xoycoin_exchange.env --link xoycoin-mysql --link xoycoin-redis xoycoin/xoycoin-exchange-cron-users

# docker run --name xoycoin-exchange-cron-users --env-file ./local.env --link xoycoin-mysql --link xoycoin-redis xoycoin/xoycoin-exchange-cron-users