FROM node:14.17.1
WORKDIR /app

COPY ./package*.json ./
RUN npm ci

COPY src ./src
CMD [ "npm", "run", "cron-eth-transfer" ]

# docker build -f Dockerfile_Cron_ETH_Transfer . -t xoycoin/xoycoin-exchange-cron-eth-transfer
# docker run --name xoycoin-exchange-cron-eth-transfer --env-file ./xoycoin_exchange.env --link xoycoin-mysql --link xoycoin-redis xoycoin/xoycoin-exchange-cron-eth-transfer

# docker run --name xoycoin-exchange-cron-eth-transfer --env-file ./local.env --link xoycoin-mysql --link xoycoin-redis xoycoin/xoycoin-exchange-cron-eth-transfer