FROM node:14.17.1
WORKDIR /app

COPY ./package*.json ./
RUN npm ci

COPY src ./src
CMD [ "npm", "run", "cron-xoy-transfer" ]

# docker build -f Dockerfile_Cron_XOY_Transfer . -t xoycoin/xoycoin-exchange-cron-xoy-transfer
# docker run --name xoycoin-exchange-cron-xoy-transfer --env-file ./xoycoin_exchange.env --link xoycoin-mysql --link xoycoin-redis xoycoin/xoycoin-exchange-cron-xoy-transfer

# docker run --name xoycoin-exchange-cron-xoy-transfer --env-file ./local.env --link xoycoin-mysql --link xoycoin-redis xoycoin/xoycoin-exchange-cron-xoy-transfer