### Get deposit by hash
GET {{url}}/deposits_companies/hash/:hash

{
  "id": "604da2e8-7c12-4237-a006-bb2137515283",
  "walletId": "51be9810-8135-4568-ac37-d7fa647f468a",
  "userId": "b3de0177-020a-11ec-8efe-0242ac110003",
  "hash": "hash-1",
  "sender": "address-1",
  "amount": "1.00000000",
  "fee": "2",
  "confirmations": "2",
  "status": "PENDING",
  "timestamp": "1970-01-01T00:00:00.000Z"
}

### Get deposits by user and wallet
GET {{url}}/deposits_companies/user/:userId/wallet/:walletId

[
  {
    "id": "604da2e8-7c12-4237-a006-bb2137515283",
    "walletId": "51be9810-8135-4568-ac37-d7fa647f468a",
    "userId": "b3de0177-020a-11ec-8efe-0242ac110003",
    "hash": "hash-1",
    "sender": "address-1",
    "amount": "1.00000000",
    "fee": "2",
    "confirmations": "2",
    "status": "PENDING",
    "timestamp": "1970-01-01T00:00:00.000Z",
    "createdAt": "2021-10-26T02:25:50.000Z",
    "updatedAt": null
  },
  {
    "id": "cc683f75-d4c1-485c-9f22-af2eac0fd3fe",
    "walletId": "51be9810-8135-4568-ac37-d7fa647f468a",
    "userId": "b3de0177-020a-11ec-8efe-0242ac110003",
    "hash": "hash-2",
    "sender": "address-2",
    "amount": "2.00000000",
    "fee": "2",
    "confirmations": "2",
    "status": "PENDING",
    "timestamp": null,
    "createdAt": "2021-10-26T02:25:50.000Z",
    "updatedAt": null
  }
]
