### Create wallet
POST {{url}}/blockchain/wallet
Content-Type: application/json
Authorization: {{token}}

{
  "seed": "d8d78d809328769b97c76b9d77d491235241bd2f42ff76d12b9c8a32ba6314c27311a2f5178baa1beb7fee55d4af6ef782d88e74529b759fdc1add4dccdf0660",
  "indexId": 1,
  "currency": "ETH"
}

### Send transaction
POST {{url}}/blockchain/send/
Content-Type: application/json
Authorization: {{token}}

{
  "from": "0x75393d51027e34c2279eDB419754155719cA05e3",
  "to": "0x14d5668FFF8a0719f6FE9A8060F8e86837e995E2",
  "amount": "0.06",
  "currency": "ETH"
}

### Send transaction (company)
POST {{url}}/blockchain/send/company
Content-Type: application/json
Authorization: {{token}}

{
  "from": "0x75393d51027e34c2279eDB419754155719cA05e3",
  "to": "0x14d5668FFF8a0719f6FE9A8060F8e86837e995E2",
  "amount": "0.1",
  "currency": "ETH"
}

### Get balance by address and currency
GET {{url}}/blockchain/balance/address/0x14d5668FFF8a0719f6FE9A8060F8e86837e995E2/currency/ETH
Content-Type: application/json
Authorization: {{token}}

### Get transaction by txId and currency
GET {{url}}/blockchain/transaction/0x3ee9c5c95f7dcd60a382e9b3d444cb472ee08c03dcdf74c4a91c0e256f4ca380/currency/ETH
Content-Type: application/json
Authorization: {{token}}

### Get transactions by txsId and currency
GET {{url}}/blockchain/transactions/txs/0x3ee9c5c95f7dcd60a382e9b3d444cb472ee08c03dcdf74c4a91c0e256f4ca380,0x47b6a4aad0e8ec84f51b7e48829f7f1d7913b33b55a27a1404e193c4526e1d7d/currency/ETH
Content-Type: application/json
Authorization: {{token}}

### Get transactions by address and currency
GET {{url}}/blockchain/transactions/address/0x14d5668FFF8a0719f6FE9A8060F8e86837e995E2/currency/ETH
Content-Type: application/json
Authorization: {{token}}

### Get block by height and currency
### height 11092874 after fork -> 11087035 berfore fork - (5839 blocks difference)
GET {{url}}/blockchain/block/height/11062722/currency/ETH
Content-Type: application/json
Authorization: {{token}}

### Ejemplo tx con data: 0x904f8e3af19f1fdbbe7a0e534b6a8f080ff6b2ad79c7a874cee22b53ee70f717
### Usar to-hex en la tx: data: toHex('mensaje')