name: Xoycoin-Exchange-Api

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: xoycoin
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: xoycoin-exchange
  NAMESPACE: xoycoin-staging
  DATABASE: xoycoin
  IMAGE: xoycoin-exchange-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # elimino el lock para permitir que se ejecute de forma adecuada el install
      - run: rm package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Configure docker
        run: |-
          gcloud --quiet auth configure-docker

      - name: Configure kubernetes
        uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Build docker image
        run: |-
          docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

      - name: Publish docker image
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

      - name: Update kubernetes deployment
        run: |-
          kubectl set image deployment/xoycoin-exchange xoycoin-exchange=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA -n $NAMESPACE
          kubectl get service/xoycoin-exchange -o wide -n $NAMESPACE
